version: '3'

services:

  spring-users:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8088:8088"
    environment:
      - DB_PORT=3306
      - DB_DBNAME=messages
      - DB_USER=root
      - DB_PASSWORD=password
    networks:
      demo_net:
        ipv4_address: 172.30.1.7

volumes:
  my-db:

networks:
  demo_net:
    external: true
