version: '3'

services:
  db-device:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'devices'
      MYSQL_ROOT_PASSWORD: 'heineken'
    ports:
      - "3307:3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      demo_net:
        ipv4_address: 172.30.1.2
  spring-users:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_IP=db-device
      - DB_PORT=3306
      - DB_DBNAME=devices
      - DB_USER=root
      - DB_PASSWORD=heineken
    networks:
      demo_net:
        ipv4_address: 172.30.1.4

volumes:
  my-db:

networks:
  demo_net:
    external: true
